config/routes.rb
Rails.application.routes.draw do
  root 'calc#input', as: 'home'
  get 'calc/input'
  get 'calc/output'
  get 'users/new'
  get 'users/show'
  get 'users/update'
  post 'users/create', to: 'users#create'
  post 'users/destroy', to: 'users#destroy'
  get 'sessions/new'
  post 'sessions/create', to: 'sessions#create'
  post 'sessions/destroy', to: 'sessions#destroy'
  resources :sessions
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :login, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calc_controller.rb
class CalcController < ApplicationController
  def input
  end

  def output
    if params[:val] == ''
      flash[:warning] = 'Fill in the field'
    elsif params[:val].scan(/\d+/).map(&:to_i).length < 10
      flash[:warning] = 'The number of entered numbers must be greater than 9!'
    end
    if flash.empty?
      val = params[:val].scan(/\d+/).map(&:to_i)
      res = CalcController.processor(val)
      @result1 = res[0]
      @result2 = res[1]
      @result3 = res[2]
    else
      redirect_to '/calc/input'
    end
  end

  def self.processor(mas)
    arr = []
    boofer = []
    cur = mas[0]
    mas.each do |i|
      if i >= cur
        boofer.push(i)
        cur = i
      else
        arr.push(boofer)
        boofer = []
        boofer.push(i)
        cur = i
      end
    end
    arr.push(boofer)
    s1 = mas.join(' ')
    s2 = composit(arr)
    s3 = maxlenseq(arr)
    [s1,s2,s3]
  end
  def self.composit(a)
    s = ""
    a.each do |i|
      s += i.join(' ')
      s += ', ' if i != a[-1]
    end
    s
  end
  def self.maxlenseq(a)
    n = []
    a.each{|i| n = i if i.length > n.length}
    n.join(' ')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        reset_session
        session[:user_id] = @user.id
        flash[:success] = "Welcome, #{@user.login}!"
        redirect_to '/calc/input'
      else
        flash[:warning] = 'Invalid e-mail or password'
        redirect_to '/sessions/new'
        return
      end
    else
      flash[:warning] = 'Invalid e-mail or password'
      redirect_to '/sessions/new'
      return
    end
  end

  def destroy
    reset_session
    flash[:success] = 'Signed out successfully'
    redirect_to '/calc/input'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :validate_input, only: :create

  def create
    unless @user.valid?
      redirect_to '/users/create'
      return
    else
      @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.login}!"
      redirect_to home_path
    end
  end

  def show
  end

  def update
  end

  def destroy
    @user = User.find(session[:user_id])
    @user.destroy
    reset_session
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calc_helper.rb
module CalcHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def validate_input
		@user = User.new(params.permit(:email, :login, :password, :password_confirmation))
		unless @user.valid?
			flash[:warning] = @user.errors.full_messages.to_sentence
		else
			flash[:success] = 'User has been created successfully!'
		end
	end
end

app/views/calc/input.html.erb
<h2 align="center">Sequences input</h2>

<% unless session[:user_id].nil? %>

<p>Task: Write a program that introduces a chain of integers (the number
of numbers is at least 10) and determines the longest monotonically increasing sequence of them.
<br/>Print the entered chain, all
the found sequences and the longest of them. When programming, use the function.</p>
<p>Enter a string of integers (the number
of numbers is at least 10):</p>
<p>If there are different characters other than integers in the sequence, they will be ignored!</p>

  <%= form_with url: '/calc/output', method: :get do |form| %>
		<p>
			<%= form.label 'Enter the sequence', class: 'form-label' %>
			<%= form.text_field :val, class: 'form-control', id: 'val-input' %>
		</p>
		<p>
			<%= form.submit 'Submit', class: 'btn btn-primary' %>
		</p>
	<% end %>
<% else %>
	<p id="loginmsg">To use this service, you need to be signed in!</p>
<% end %>

app/views/calc/output.html.erb
<h1>Result</h1>

<table class="table">
<thead><tr><th>Name</th><th>Result</th></tr></thead>
<tbody><tr><td>The original sequence:</td><td><%= @result1 %></td></tr>
<tr><td>Subsequences of numbers:</td><td><%= @result2 %></td></tr>
<tr><td>Longest subsequence:</td><td><%= @result3 %></td></tr></tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppLR12</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <style type="text/css">
      .table {
        border: none;
        margin-bottom: 20px;
        border-collapse: separate;
      }
      .table thead th {
        font-weight: bold;
        text-align: left;
        border: none;
        padding: 10px 15px;
        background: #EDEDED;
        font-size: 14px;
        border-top: 1px solid #ddd;
      }
      .table tr th:first-child, .table tr td:first-child {
        border-left: 1px solid #ddd;
      }
      .table tr th:last-child, .table tr td:last-child {
        border-right: 1px solid #ddd;
      }
      .table thead tr th:first-child {
        border-radius: 20px 0 0 0;
      }
      .table thead tr th:last-child {
        border-radius: 0 20px 0 0;
      }
      .table tbody td {
        text-align: left;
        border: none;
        padding: 10px 15px;
        font-size: 14px;
        vertical-align: top;
      }
      .table tbody tr:nth-child(even) {
        background: #F8F8F8;
      }
      .table tbody tr:last-child td{
        border-bottom: 1px solid #ddd;
      }
      .table tbody tr:last-child td:first-child {
        border-radius: 0 0 0 20px;
      }
      .table tbody tr:last-child td:last-child {
        border-radius: 0 0 20px 0;
      }
    </style>
    <style>
      body {
      background: #00FFFF;
      }
      .navbar {
      background: #00CED1;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg" class="navbar">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Sequences', '/calc/input', class: 'nav-link active' %>
            </li>
            <% if session[:user_id].nil? %>
              <li class="nav-item">
                <%= link_to 'Sign in', '/sessions/new', class: 'nav-link active' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', '/users/new', class: 'nav-link active' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign out', sessions_destroy_path, data: {turbo_method: :delete}, class: 'nav-link active' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <br/>
    <div class="container">
      <% flash.each do |type, msg| %>
        <% if type == 'success' %>
          <div class="alert alert-success">
            <%= msg %>
          </div>
        <% elsif type == 'warning' %>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
<h2 align="center">Sign up</h2>

<%= form_with url: 'create', method: :post do |form| %>
	<p>
		<%= form.label 'Enter e-mail', class: 'form-label' %>
		<%= form.email_field :email, placeholder: 'E-mail', class: 'form-control', id: 'email' %>
	</p>
	<p>
		<%= form.label 'Enter login', class: 'form-label' %>
		<%= form.text_field :login, placeholder: 'Login', class: 'form-control', id: 'login' %>
	</p>
	<p>
		<%= form.label 'Enter password', class: 'form-label' %>
		<%= form.password_field :password, class: 'form-control', id: 'password' %>
	</p>
	<p>
		<%= form.label 'Confirm password', class: 'form-label' %>
		<%= form.password_field :password_confirmation, class: 'form-control', id: 'password-confirmation' %>
	</p>
	<p>
		<%= form.submit 'Sign up', class: 'btn btn-primary' %>
	</p>
<% end %>
<%= link_to 'Already have an account? Sign in!', '../sessions/new' %>

app/views/users/show.html.erb
<h2 align="center">All users</h2>

<% users = User.all %>
<% users.each do |user| %>
	<p>
		<%= user.email %>
		 ---
		<%= user.login %><br/>
	</p>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>